### ISSUE TITLE
[Catalog] Placeholder in comment fields is white instead of gray after switching to black theme

### ISSUE THREAD

**Issue by PetroMatiiv** [ita-social-projects/horondi_admin#1083]
**Environment:** Dell Inspiron 3576, Windows 10б Google Chrome 94.0.4606.61
**Type** UI
**Reproducible**: Always

**Preconditions**

1. Go to https://horondi-front-staging.azurewebsites.net/login
2. Log in using google account
3. Switch theme to Black

**Steps to reproduce**

1. Click on 'Burger menu'
2. Choose Backpacks
3. Choose Rolltop
4. Click on Rolltop blue
5. Scroll to comment field
6. Pay attention to comment field (Placeholder)

**Actual result**
Colour of placeholder is white instead of gray. Impossible to read placeholder

![Incorrect 1](https://user-images.githubusercontent.com/91191986/135691059-111e9e80-b7ac-4cb3-af2d-a630eb80440a.jpg)

**Expected result**
Colour of placeholder is gray instead of white. Possibility to read placeholder

![Correct](https://user-images.githubusercontent.com/91191986/135691055-603a2156-bd44-4f97-b8fb-a90ac5f72b75.jpg)

**Priority**: Low

**Severity**: Minor

**Comment by NataliiaPalyg** [comment]
When user places the cursor in the comment field text of placeholder are visible partly
![image](https://user-images.githubusercontent.com/92394070/142294691-c0edf0eb-28da-43bf-afe7-5e0241d35b78.png)
