### ISSUE TITLE
(SP:5)Write enzyme test for `ContactsForm` component

### ISSUE THREAD

**Issue by Kiyooooko** [ita-social-projects/horondi_admin#443]
Using Enzyme lib write test for React component 

You should test:
- [ ] component rendering
- [ ] state changes
- [ ] props changes
- [ ] event handlers
- [ ] if...else
- [ ] classes 
- [ ] hooks
- [ ] children components

**Comment by ostgit12** [comment]
Hristina Sokyrko has the same task and done it with good coverage
