### ISSUE TITLE
(SP:1)[Admin page: Категорії] The wrong error message appears after entering already existing names

### ISSUE THREAD

**Issue by anastas184** [ita-social-projects/horondi_admin#637]
Check if the same category name exists in the base onBlur and show an error under the field that:
'Така категорія вже існує'
______________________________________________________________________________________
Environment: Windows Server 2019 Standart 64-bit, Google Chrome v.88.0.4324.190
Reproducible: always
Build found: the last commit from https://github.com/ita-social-projects/horondi_admin

Pre-conditions:
Go to https://horondi-admin-staging.azurewebsites.net
Log into Administrator page as Administrator: login 'qualityadmin@gmail.com', password 'qualityControl123'
Click on 'Category' menu item.

Steps to reproduce:
1. Click 'Додати категоріїю' button
2. Click on 'Завантажити' button and upload photo
3. Enter valid data into the field 'Код категорії'
4. Enter the already existing name in field 'Назва категорії'
5. Enter the already existing name in the field 'Category name'
6. Click on 'Зберегти' button
Actual result: The category is not created. Error message 'Response not successful: Received status code 500' appears
Expected result: The category is not created. Error message 'Така категорія вже існує' appears

[User story] (https://jira.softserve.academy/browse/LVHRB-15)
[TC] (https://jira.softserve.academy/browse/LVHRB-90)

**Comment by yuliiakucher** [comment]
The issue is already resolved

![image](https://user-images.githubusercontent.com/61886864/114177292-e690b080-9944-11eb-9367-6c5eb9338d89.png)
