### ISSUE TITLE
[Admin Page: Категорії] The wrong error messages appear after entering limit of characters in text fields

### ISSUE THREAD

**Issue by anastas184** [ita-social-projects/horondi_admin#638]
Environment: Windows Server 2019 Standart 64-bit, Google Chrome v.88.0.4324.190
Reproducible: always
Build found: the last commit from https://github.com/ita-social-projects/horondi_admin

Pre-conditions:
Go to https://horondi-admin-staging.azurewebsites.net
Log into Administrator page as Administrator: login 'qualityadmin@gmail.com', password 'qualityControl123'
Click on 'Category' menu item.

Steps to reproduce:

1. Click 'Додати категоріїю' button
2. Click on 'Завантажити' button and upload photo
3. Enter less than 2 characters into the field 'Код категорії'
4. Enter less than 2 characters in field 'Назва категорії'
5. Enter less than 2 characters in the field 'Category name'
6. Click on 'Зберегти' button
Actual result: Error message 'Мінімум 2 символи' appears near text fields 
Expected Result: 1) Error message 'Це поле повинно містити від 2 до 30 символів' appears near 'Код категорії'
                           2) Error message 'Назва повина містити від 2 до 50 символів' appears near 'Назва категорії'
                           3) Error message 'Name of category повинно містити від 2 до 50 символів’' appears near 'Category name'

[User story] (https://jira.softserve.academy/browse/LVHRB-15)
[TC] (https://jira.softserve.academy/browse/LVHRB-46)
![error_messages](https://user-images.githubusercontent.com/61836366/110761974-fee3b180-8258-11eb-952b-d007b3f7e736.png)

**Comment by grebiniuk** [comment]
Fixed in the other task
