### ISSUE TITLE
[Admin Page: Категорії] The wrong error messages appear after entering incorrect data in text fields

### ISSUE THREAD

**Issue by anastas184** [ita-social-projects/horondi_admin#642]
Environment: Windows Server 2019 Standart 64-bit, Google Chrome v.88.0.4324.190
Reproducible: always
Build found: the last commit from https://github.com/ita-social-projects/horondi_admin

Pre-conditions:
Go to https://horondi-admin-staging.azurewebsites.net
Log into Administrator page as Administrator: login 'qualityadmin@gmail.com', password 'qualityControl123'
Click on 'Category' menu item.

Steps to reproduce:

1. Click 'Додати категоріїю' button
2. Click on 'Завантажити' button and upload photo
3. Enter special characters ('@3$$#@') in the field 'Код категорії'
4. Enter English letters, special symbols, digits ('Belt@1') in the field 'Назва категорії'
5. Enter cyrylic letters, special characters, digits ('Пояс@1') in the field 'Category name'
6. Click on 'Зберегти' button
Actual result: 1) Error message 'Поле не може містити спеціальні символи' appears near 'Код категорії'
                      2) Error message 'Поле може містити тільки українські літери та цифри' appears near 'Назва категорії'
                      3)Error message 'Поле може містити тільки англійські літери та цифри' appears near 'Category name'
Expected Result: 1) Error message ‘Поле ‘Код категорії’ не може містити спеціальні символи’ appears near 'Код категорії'
                           2) Error message 'Поле Назва категорії може містити тільки українські літери, цифри та спецсимволи’ 
                               appears near 'Назва категорії'
                           3) Error message 'Поле Name of Category може містити тільки латинські літери, цифри та спецсимволи’
                              appears near 'Category name'
[User story] (https://jira.softserve.academy/browse/LVHRB-15)
[TC] (https://jira.softserve.academy/browse/LVHRB-66
![11](https://user-images.githubusercontent.com/61836366/110849244-ac85ad80-82b7-11eb-8ff9-19048dccebdd.png)
)

**Comment by grebiniuk** [comment]
Fixed in the different task
