### ISSUE TITLE
[Рюкзаки]  Different price of item when select it

### ISSUE THREAD

**Issue by SvitlanaNykolyn** [ita-social-projects/horondi_admin#940]
![actual](https://user-images.githubusercontent.com/88825304/130264074-4edee408-0dcf-4d4e-9918-8478be6c226b.png)
![actual 1](https://user-images.githubusercontent.com/88825304/130264099-f0b5ec27-10d9-4d0c-9cb8-c12089e27d85.png)

https://user-images.githubusercontent.com/88825304/130264138-a08365b3-441b-4e1d-93af-b17357904281.mp4

**Environment:** Windows 7 Google Chrome Версія 92.0.4515.159
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/horondi_admin
E.g. "commit 147fa44"

**Steps to reproduce**
1. Go to https://horondi-front-staging.azurewebsites.net/login
2. Click on the  'Рюкзаки'
3. Click on the ' Роллтоп'
4.  Select 'Роллтоп червоний' or 'Роллтоп жовтий'

**Actual result**
Different price of items when select it

**Expected result**
The price should be the same on all pages

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by NetkachovaAnastasiya** [comment]
This task I think related to this one
https://github.com/ita-social-projects/horondi_client_fe/issues/657
